name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy to Render
      run: |
        curl -X POST -H "Authorization: Bearer rnd_pmAGKHvDxScpGCcnG1EeOTR4at1S" \
        -H "Content-Type: application/json" \
        -d '{"serviceId": "srv-cu1m6p9u0jms738k6620"}' \
        https://api.render.com/deploy
