name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python train_model.py

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Render
        uses: render-examples/deploy-render@v1
        with:
          service: flask-app  # Replace with your Render service name
