name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Train the model
      - name: Train model
        run: |
          python train_model.py

      # Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cu1m6p9u0jms738k6620?key=${{ secrets.MR55 }}"
