name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-train:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Python environment
    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Train the machine learning model
    - name: Train Model
      run: |
        python train_model.py
        ls -lh  # List the directory to confirm model.pkl and scaler.pkl are created

    # Step 5: Start Flask app
    - name: Start Flask App
      run: |
        nohup python app.py &  # Start Flask in the background
        sleep 5  # Allow time for the app to initialize

    # Step 6: Deploy to Render
    - name: Deploy to Render
      run: |
        curl -X POST \
        -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
        https://api.render.com/deploy/srv-cu1m6p9u0jms738k6620?key=CF2Hy2JToYI
