name: Render Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Test application
        run: python -m unittest discover  # Optional for tests

      - name: Deploy to Render
        run: render-python deploy
