name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python train_model.py

    - name: Deploy to Render
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"serviceName": "my-ml-app44"}' \
        https://api.render.com/deploy
